# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scan4log4shell < Formula
  desc "Scanner to detect vulnerable log4j versions on your file-system or to send specially crafted requests and catch callbacks of systems that are impacted by log4j log4shell vulnerability (CVE-2021-44228)"
  homepage "https://github.com/hupe1980/scan4log4shell"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/scan4log4shell/releases/download/v0.5.0/scan4log4shell_Darwin_arm64.tar.gz"
      sha256 "cef3e2a38fc1d3cb8d0a6b76e78d706f6833f33c63b0458d83ef90a5b31ca2bb"

      def install
        bin.install "scan4log4shell"
        bash_completion.install "completions/scan4log4shell.bash" => "scan4log4shell"
        zsh_completion.install "completions/scan4log4shell.zsh" => "_scan4log4shell"
        fish_completion.install "completions/scan4log4shell.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/scan4log4shell/releases/download/v0.5.0/scan4log4shell_Darwin_x86_64.tar.gz"
      sha256 "0d1cb1c125f0482ca8355bf6d6d3c5ded9fa8eecb6cd30f4de6def0dc19489f7"

      def install
        bin.install "scan4log4shell"
        bash_completion.install "completions/scan4log4shell.bash" => "scan4log4shell"
        zsh_completion.install "completions/scan4log4shell.zsh" => "_scan4log4shell"
        fish_completion.install "completions/scan4log4shell.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/scan4log4shell/releases/download/v0.5.0/scan4log4shell_Linux_armv6.tar.gz"
      sha256 "6b8c2007004f266ba8581fe2d3dc457e0285ecc5f5a657a00042b27ea0cea9d9"

      def install
        bin.install "scan4log4shell"
        bash_completion.install "completions/scan4log4shell.bash" => "scan4log4shell"
        zsh_completion.install "completions/scan4log4shell.zsh" => "_scan4log4shell"
        fish_completion.install "completions/scan4log4shell.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/scan4log4shell/releases/download/v0.5.0/scan4log4shell_Linux_x86_64.tar.gz"
      sha256 "0647c2a062b8d979f4adcf800da443adacf62e50f4b03731286fd2fdf90fa74d"

      def install
        bin.install "scan4log4shell"
        bash_completion.install "completions/scan4log4shell.bash" => "scan4log4shell"
        zsh_completion.install "completions/scan4log4shell.zsh" => "_scan4log4shell"
        fish_completion.install "completions/scan4log4shell.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/scan4log4shell/releases/download/v0.5.0/scan4log4shell_Linux_arm64.tar.gz"
      sha256 "1d896cf7fc04cd9da7ffb53c1c263c87d4d263b07181897e94a2256bef9cb820"

      def install
        bin.install "scan4log4shell"
        bash_completion.install "completions/scan4log4shell.bash" => "scan4log4shell"
        zsh_completion.install "completions/scan4log4shell.zsh" => "_scan4log4shell"
        fish_completion.install "completions/scan4log4shell.fish"
      end
    end
  end

  test do
    system "#{bin}/scan4log4shell -v"
  end
end
